### ISSUE TITLE
Try the Application

### ISSUE THREAD

**Issue by CreePyan** [MartyrPher/SMAPI-Android-Installer#1]
Hi...

I want to try the SMAPI application

even though it's not finished, I just want to try it

**Comment by MartyrPher** [comment]
Hey CreePyan,

It's a little iffy at the moment. It crashes on some devices and works on others. I don't think it's ready to be built into an apk yet. But feel free to import the project into an IDE and build it yourself.

**Comment by CreePyan** [comment]
give me a link when it's finished 😉
