### ISSUE TITLE
Stardew Valley 1.4.5.141

### ISSUE THREAD

**Issue by ANameJustForThisSite** [MartyrPher/SMAPI-Android-Installer#109]
Can't use SMAPI after latest version of Stardew Valley. Stuck on "Loading..." when resuming a save file.

**Comment by ANameJustForThisSite** [comment]
SMAPI was not the cause.

**Comment by bev0191** [comment]
What was your cause if you don't mind me asking? Also having issues loading saves

**Comment by ANameJustForThisSite** [comment]
If you're having the same problem as me, I managed to circumvent the issue by reloading the previous file (the one with "_old" at the end by just renaming them through a folder manager). But yesterday i was faced with both save files (day 21 and 22) having the infinite loading screen and without any backup. You might want to do that frequently until theres a fix.
If this helps, maybe we have mods in common: https://smapi.io/log/bdeb31bf917c44b8a1252092b0cce6b2
