### ISSUE TITLE
My Saves Dissapear

### ISSUE THREAD

**Issue by Unacornexe** [MartyrPher/SMAPI-Android-Installer#111]
Ever since I installed specific mods, my saves dissapeared completely...

Before they dissapeared, I added these mods:
-Happy Birthday by Alpha_Omegasis; https://www.nexusmods.com/stardewvalley/mods/520 
-Stardust Core by Alpha_Omegasis;
https://www.nexusmods.com/stardewvalley/mods/2341
- Automatic Gates by ScheKaa; https://www.nexusmods.com/stardewvalley/mods/3109?tab=files
-Entoarox Framework by Entoarox; https://www.nexusmods.com/stardewvalley/mods/2269
-Furniture Anywhere by Entoarox; https://www.nexusmods.com/stardewvalley/mods/2276
-Tractor Mod by Pathoschild; https://www.nexusmods.com/stardewvalley/mods/1401?tab=files&file_id=23488 

Here is my log:
https://smapi.io/log/8bbf3a4f429042ba94a0e35af3424d1f

Thank you for your help! 😊

**Comment by ANameJustForThisSite** [comment]
Remove Entoarox Framework and it should work. Entoarox has said that his mods don't work right now on android. Sadly that means mods requiring it cannot be installed either.
