### ISSUE TITLE
Can't load save file

### ISSUE THREAD

**Issue by bev0191** [MartyrPher/SMAPI-Android-Installer#113]
Hey everyone, having issues loading saved games and my smapi log says smapi is the wrong version. I'm not great with modding so any advice is much appreciated

https://smapi.io/log/9c87a25dba9043968381833243b938b4

**Comment by Skishe** [comment]
Hey we meet again here

From reddit to github haha

**Comment by bev0191** [comment]
> Hey we meet again here
> 
> From reddit to github haha

Hahaha, hello again saviour of my save file!
