### ISSUE TITLE
Smapi 3.3.2 update???

### ISSUE THREAD

**Issue by LunaDyer** [MartyrPher/SMAPI-Android-Installer#118]
Already have a date foreseen for updating the smapi? several mods are requiring version 3.3.2, I can't even open the game via smapi

**Comment by vuongvan** [comment]
![Screenshot_20200313-173838](https://user-images.githubusercontent.com/5875055/76613938-aef0e280-6551-11ea-96bd-ded81472a230.png)
[Link download](https://github.com/ZaneYork/SMAPI-Android-Installer/releases)

**Comment by LunaDyer** [comment]
> ![Screenshot_20200313-173838](https://user-images.githubusercontent.com/5875055/76613938-aef0e280-6551-11ea-96bd-ded81472a230.png)
> [Link download](https://github.com/ZaneYork/SMAPI-Android-Installer/releases)

Tysm
