### ISSUE TITLE
Smapı Crash

### ISSUE THREAD

**Issue by DemiurgeSan** [MartyrPher/SMAPI-Android-Installer#128]
Hey on android store version of smapı go crash after open. Can anyone help. 
![Screenshot_2020-05-24-13-27-53-727_com miui bugreport](https://user-images.githubusercontent.com/65851738/82751874-eb975080-9dc2-11ea-9169-9d8a0ceacf65.jpg)
![Screenshot_2020-05-24-13-28-00-431_com miui bugreport](https://user-images.githubusercontent.com/65851738/82751875-ed611400-9dc2-11ea-8eac-02da92bf71f6.jpg)

**Comment by Pathoschild** [comment]
Hi! That version of SMAPI is [ZaneYork/SMAPI-Android-Installer](https://github.com/ZaneYork/SMAPI-Android-Installer), so you should report issues there.

**Comment by DemiurgeSan** [comment]
> Hey on android store version of smapı go crash after open. Can anyone help.
> ![Screenshot_2020-05-24-13-27-53-727_com miui bugreport](https://user-images.githubusercontent.com/65851738/82751874-eb975080-9dc2-11ea-9169-9d8a0ceacf65.jpg)
> ![Screenshot_2020-05-24-13-28-00-431_com miui bugreport](https://user-images.githubusercontent.com/65851738/82751875-ed611400-9dc2-11ea-8eac-02da92bf71f6.jpg)
