### ISSUE TITLE
Update for SMAPI 2.11.3

### ISSUE THREAD

**Issue by MartyrPher** [MartyrPher/SMAPI-Android-Installer#13]
Pathoschild has recently updated SMAPI to version `2.11.3`, the Android version should be updated as well.

**Comment by CreePyan** [comment]
Why Its So Late ? 
Sorry for my Bad English

**Comment by momn17** [comment]
S

**Comment by MartyrPher** [comment]
The new semester started and I have a new part time job so I don't have much time to work on it sadly, BUT ALAS, I just pushed out the new release [here](https://github.com/MartyrPher/SMAPI-Android-Installer/releases/latest). Cheers!

**Comment by MartyrPher** [comment]
Since the release is out, I'm closing this issue. Cheers!
