### ISSUE TITLE
Custom Farming Redux

### ISSUE THREAD

**Issue by Skishe** [MartyrPher/SMAPI-Android-Installer#14]
Seems to break the game. Crashes after 2 seconds upon loading a save.

**Comment by MartyrPher** [comment]
That's an Harmony patch that's broken causing the crash. It's on my TODO list but I still haven't gotten around to it.

**Comment by alvinaz-007** [comment]
you can fix them? i need CFR ?

**Comment by yungbawal** [comment]
I am also having the same issue with this mod installed.
https://log.smapi.io/PuHcdRCG
pls fix :(

**Comment by MartyrPher** [comment]
Routine has updated CFR to work with Android, this is an experimental release. So if you run into any issues you can post your log and problem here. I will relay the information to Routine to see what they can do. The latest version on the nexus is what you need.

https://www.nexusmods.com/stardewvalley/mods/991?tab=files

Cheers!
