### ISSUE TITLE
Package invalid error

### ISSUE THREAD

**Issue by ij1738** [MartyrPher/SMAPI-Android-Installer#141]
When downloading on android S22 Ultra exynos 2200 it only gives me a package invalid, downloading the app was okay but the next part doesn't work

**Comment by ij1738** [comment]
Needed correct game version

**Comment by Skishe** [comment]
> Needed correct game version

Why are you even on here? This is SMAPI for 1.3 stardew.

Zane York has the 1.4 smapi... And i guess Alpha version for 1.5 stardew.
