### ISSUE TITLE
Error When Load Save

### ISSUE THREAD

**Issue by CreePyan** [MartyrPher/SMAPI-Android-Installer#16]
https://log.smapi.io/TzhGp80s

I Think This Error Because CustomNPCFixes

**Comment by Skishe** [comment]
I dont think you installed SVE correctly. I mean it works completely fine for me.

**Comment by CreePyan** [comment]
I installed it correctly

**Comment by Skishe** [comment]
Wait... did you install the town map correctly? The error points out to the 4 new npc in SVE so probably try to trace it.

**Comment by MartyrPher** [comment]
Hmm, I have seen this error before but I cannot remember what caused it. Last time it was something with TMX Loader but that doesn't look like the case in the log. Does this only happen when trying to load your save from a backup or everytime?

**Comment by CreePyan** [comment]
No

**Comment by CreePyan** [comment]
it always happens if there is an event when leaving the house
