### ISSUE TITLE
About entoarox framework broken code error

### ISSUE THREAD

**Issue by Skishe** [MartyrPher/SMAPI-Android-Installer#22]
Broken code in EntoaroxFramework.dll: reference to Netcode.NetDictionary`5<Microsoft.Xna.Framework.Vector2,StardewValley.TerrainFeatures.TerrainFeature,Netcode.NetRef`1<StardewValley.TerrainFeatures.TerrainFeature>,StardewValley.SerializableDictionary`2<Microsoft.Xna.Framework.Vector2,StardewValley.TerrainFeatures.TerrainFeature>,StardewValley.Network.NetVector2Dictionary`2<StardewValley.TerrainFeatures.TerrainFeature,Netcode.NetRef`1<StardewValley.TerrainFeatures.TerrainFeature>>>.GetEnumerator (no such method).

What does this lead to anyway? Although its working, its been bothering me for a long time now.

**Comment by MartyrPher** [comment]
I'm actually not sure. I have looked into it. But I haven't gotten to find out exactly where that broken code shows up in the mod.
