### ISSUE TITLE
MonoMod RuntimeDetour Game Crash

### ISSUE THREAD

**Issue by RicewithSoySauce** [MartyrPher/SMAPI-Android-Installer#25]
In the Error-log says
"Critical app domain exception: System.Exception: This method should've been detoured! at MonoMod.RuntimeDetour.Plataforms.DetourRuntimeILPlataform._SelftestFetRefPtr () [0x0000f] in
<fdfbe717021d449d9321115f786348b3> :0

**Comment by MartyrPher** [comment]
Can you try out this Installer, your Android processor doesn't allow for Harmony mods so I had to edit SMAPI to disable it on Android versions 5.1.1 and below.

https://files.catbox.moe/3s6ov9.apk

**Comment by RicewithSoySauce** [comment]
So, there will be mods that won't work well, right?

**Comment by CreePyan** [comment]
I am only want more mod compatibility

**Comment by Raito007** [comment]
The mod that i have confirm will not work is mods that require Pytk to work. Since Harmony is disabled, mods that require it will also not work.

**Comment by Monouichan** [comment]
will this SMAPI installer be updated? I just downloaded this on my old Samsung tablet and it says it requires game version 1.331, but my game is running the latest version.

**Comment by MartyrPher** [comment]
There is a new pinned issue that will house every released Monomod detour crash. #81 .Closing this one now.
