### ISSUE TITLE
Update for SV 1.34

### ISSUE THREAD

**Issue by Ryan-coder** [MartyrPher/SMAPI-Android-Installer#27]
![Screenshot_20191022_165830](https://user-images.githubusercontent.com/43433019/67271496-34b1ba00-f4ed-11e9-8df6-905f6078b578.jpg)

**Comment by minervamaga** [comment]
Does the current version not work with that update?  It looks like the US and possibly other areas don't have that version number, as we're still on 1.331 with a last update in August.
