### ISSUE TITLE
Error "dlopen" on Android 7.1.2 (RR)

### ISSUE THREAD

**Issue by Yuhanes** [MartyrPher/SMAPI-Android-Installer#3]
Catlog <spoiler>07-14 22:06:53.757 I/ActivityManager(426): START u0 {act=android.intent.action.MAIN cat=[android.intent.category.LAUNCHER] flg=0x10200000 cmp=com.martyrpher.stardewvalley/md5723872fa9a204f7f942686e9ed9d0b7d.SMainActivity bnds=[135,552][247,721]} from uid 10060 on display 0
07-14 22:06:53.770 I/WindowManager(426): setFocusedApp token: Token{9499db0 ActivityRecord{e736cf3 u0 com.martyrpher.stardewvalley/md5723872fa9a204f7f942686e9ed9d0b7d.SMainActivity t94}} requestedOrientation: 6
07-14 22:06:53.837 I/ActivityManager(426): Start proc 4559:com.martyrpher.stardewvalley/u0a91 for activity com.martyrpher.stardewvalley/md5723872fa9a204f7f942686e9ed9d0b7d.SMainActivity
07-14 22:06:54.190 W/monodroid(4559): Trying to load sgen from: /data/app/com.martyrpher.stardewvalley-1/lib/arm/libmonosgen-2.0.so
07-14 22:06:55.933 W/WindowManager(426): Force clearing freeze: AppWindowToken{549a3ae token=Token{9499db0 ActivityRecord{e736cf3 u0 com.martyrpher.stardewvalley/md5723872fa9a204f7f942686e9ed9d0b7d.SMainActivity t94}}}
07-14 22:06:56.857 E/linker  (4559): library "/system/lib/libdl.so" ("/system/lib/libdl.so") needed or dlopened by "/data/app/com.martyrpher.stardewvalley-1/lib/arm/libmonosgen-2.0.so" is not accessible for the namespace: [name="classloader-namespace", ld_library_paths="", default_library_paths="/data/app/com.martyrpher.stardewvalley-1/lib/arm:/data/app/com.martyrpher.stardewvalley-1/base.apk!/lib/armeabi-v7a", permitted_paths="/data:/mnt/expand:/data/data/com.martyrpher.stardewvalley"]
07-14 22:06:57.270 I/MonoDroid(4559):   at StardewModdingAPI.SMainActivity.OnCreatePartTwo () [0x00080] in <ef39ead2ccf54971b7b6ac910adbde82>:0 
07-14 22:06:57.270 I/MonoDroid(4559):   at StardewModdingAPI.SMainActivity.CheckAppPermissions () [0x00015] in <ef39ead2ccf54971b7b6ac910adbde82>:0 
07-14 22:06:57.270 I/MonoDroid(4559):   at StardewModdingAPI.SMainActivity.OnCreate (Android.OS.Bundle bundle) [0x000c0] in <ef39ead2ccf54971b7b6ac910adbde82>:0 
07-14 22:06:57.523 E/AndroidRuntime(4559): Process: com.martyrpher.stardewvalley, PID: 4559
07-14 22:06:57.523 E/AndroidRuntime(4559):   at StardewModdingAPI.SMainActivity.OnCreatePartTwo () [0x00080] in <ef39ead2ccf54971b7b6ac910adbde82>:0 
07-14 22:06:57.523 E/AndroidRuntime(4559):   at StardewModdingAPI.SMainActivity.CheckAppPermissions () [0x00015] in <ef39ead2ccf54971b7b6ac910adbde82>:0 
07-14 22:06:57.523 E/AndroidRuntime(4559):   at StardewModdingAPI.SMainActivity.OnCreate (Android.OS.Bundle bundle) [0x000c0] in <ef39ead2ccf54971b7b6ac910adbde82>:0 
07-14 22:06:57.525 W/ActivityManager(426):   Force finishing activity com.martyrpher.stardewvalley/md5723872fa9a204f7f942686e9ed9d0b7d.SMainActivity
07-14 22:06:58.029 W/ActivityManager(426): Activity pause timeout for ActivityRecord{e736cf3 u0 com.martyrpher.stardewvalley/md5723872fa9a204f7f942686e9ed9d0b7d.SMainActivity t94 f}
07-14 22:06:58.165 I/WindowManager(426): Failed to capture screenshot of Token{9499db0 ActivityRecord{e736cf3 u0 com.martyrpher.stardewvalley/md5723872fa9a204f7f942686e9ed9d0b7d.SMainActivity t94 f}} appWin=Window{e9b2f47 u0 Starting com.martyrpher.stardewvalley} drawState=4
07-14 22:06:58.856 W/ActivityManager(426):   Force finishing activity com.martyrpher.stardewvalley/md5723872fa9a204f7f942686e9ed9d0b7d.SMainActivity
07-14 22:06:58.860 I/ActivityManager(426): Killing 4559:com.martyrpher.stardewvalley/u0a91 (adj 200): crash
07-14 22:07:00.654 W/NotificationService(426): Object died trying to hide notification android.app.ITransientNotification$Stub$Proxy@191f47e in package com.martyrpher.stardewvalley</spoiler>

**Comment by MartyrPher** [comment]
I haven't see this error before, I'm still looking into it if it's still a problem?

**Comment by MartyrPher** [comment]
I have looked into this issue and it seems to be a warning more than an error as I am getting the same error in Android Studio when just building the apk. Looks like it doesn't cause any harm. I'll reopen the issue if it pops up with a vengeance.
