### ISSUE TITLE
Corrupt File

### ISSUE THREAD

**Issue by Unacornexe** [MartyrPher/SMAPI-Android-Installer#34]
Hello. 
When I open The Smapi installer and I press install, it gets the Base signed apk, but When I install the actual Smapi apk (based signed apk), it says:
"App not installed. 
The file Seem Corrupt" 
Please help me solve this issue. Thank you.

**Comment by Unacornexe** [comment]
Edit: Okay so I Found out that if this is an issue to some of you, you can just do the following:
1) Download MT manager (I suggest you download an online Apk if the free version isnt in your app store)
2) Open MT Manager and find the SMAPI Android installer and tap it to view it
3) there will be a base.Sign.apk that is the Actual SMAPI App
4) Tap it and press function to sign again
 5) once its done, it will say base.signed.sign.apk and you can download it without the "corrupt file Error" 

I hope someone finds this info useful, have a nice day!! 😁

**Comment by Unacornexe** [comment]
Edit 2: Okay, it crashes when I Skip to the first day...is it because there is too many mods...?

**Comment by MartyrPher** [comment]
Can you post your log to https://log.smapi.io/ and share it here?

**Comment by Unacornexe** [comment]
> Can you post your log to https://log.smapi.io/ and share it here?

There isnt really much log to show, because when using 1.92, it doesn't download the smapi. When it installs, it just says:  "the package appears to be corrupt"  here is a screen shot too. I'm Using an LG stylo 3
![Screenshot_2019-12-01-23-13-43](https://user-images.githubusercontent.com/58234394/69930253-8ce6bf00-1490-11ea-8174-6a2fa82835a9.png)

**Comment by Unacornexe** [comment]
Since This isn't Much of an issue anymore, I'm closing It
