### ISSUE TITLE
SMAPI 3.0 and Stardew Valley 1.4

### ISSUE THREAD

**Issue by MartyrPher** [MartyrPher/SMAPI-Android-Installer#35]
SMAPI 3.0 has released for Stardew Valley 1.4, since SMAPI 3.0 is conditioned specifically for Stardew Valley 1.4, Android will not get SMAPI 3.0 until Stardew Valley 1.4 is released for mobile. 

Also please consider this when grabbing new mod files/updating already downloaded mods.

> WARNING: many mod updates are for Stardew Valley 1.4, which is not available on Android yet. Make sure to back up the previous mod version before attempting to install updates.

**Comment by ckgio99** [comment]
1.4 has been released. Please update SMAPI. Version 0.9.2 not work on 1.4
Apk: https://bit.ly/37VOyx1
Obb: https://bit.ly/36VuREp

**Comment by MartyrPher** [comment]
Hello! 
Please do not share links to copies of the game. 
I have received the update and have a RC of SMAPI 3.2.0.

If you want to give the RC a shot, then here is a link to it. 
https://files.catbox.moe/fgcub5.apk

**Comment by ckgio99** [comment]
Thank you very much!
I have buy this game on Play Store. Sorry for my mistake.

**Comment by MrT3a** [comment]
@MartyrPher you're awesome ! 
Will try the RC as soon as possible to check for any problem that it may have ^^

**Comment by ruleofrose** [comment]
Stardew Valley 1.4 is out in Android * o * but the latest update of Smapi do not work :d with the 1.4 update :dancing_women:

**Comment by cookieraider101** [comment]
It doesn't work on galaxy s10. Hope there is a fix. Thanks dev!!!

**Comment by MartyrPher** [comment]
@cookieraider101 SMAPI Android is developed and tested on my galaxy s10. Can you provide a little more information what exactly isn't working?

**Comment by kaedehideki** [comment]
Hello. Just asking did The RC work with Json Asset and space core mod? I can't make it work on my android.

**Comment by jembenk666** [comment]
bug in console command,why i cant command world_clear ?? not only that for all of command

**Comment by NhatHao252** [comment]
Smapi don't work in my device. (Android 4.4)

**Comment by c33you** [comment]
Report sir, some important mods(for me xD) doesn't works
log : https://smapi.io/log/0eab20e0cc5c41388b463f2d082af9a4

**Comment by CookiesGirl** [comment]
Hi ! 
I'm on Galaxy Tab A 2016, Android 8.1.0 with Stardew Valley 1.4 (maj 7/02/2020) your release 0.9.2
and it doesn't work :/ 

I have this message on SMAPI-lastest.txt 
![84347382_491253218226912_4724895137237303296_n](https://user-images.githubusercontent.com/50276655/74062170-f2ee4600-49ed-11ea-99a4-d1f786bf6939.jpg)

I don't understand this :/

**Comment by MrT3a** [comment]
> Report sir, some important mods(for me xD) doesn't works
> log : https://smapi.io/log/0eab20e0cc5c41388b463f2d082af9a4

There is a fix for Stardust Core on the Issue page of Nexusmod. 
For the other mods raising exceptions, could you check if you have the latest version of each of these mods (PyTK, SpaceCore and Entoarox Framework) ?

**Comment by c33you** [comment]
Report sir, some important mods(for me xD) doesn't works
log : https://smapi.io/log/0eab20e0cc5c41388b463f2d082af9a4


> > Report sir, some important mods(for me xD) doesn't works
> > log : https://smapi.io/log/0eab20e0cc5c41388b463f2d082af9a4
> 
> There is a fix for Stardust Core on the Issue page of Nexusmod.
> For the other mods raising exceptions, could you check if you have the latest version of each of these mods (PyTK, SpaceCore and Entoarox Framework) ?

yeah Stardust Core already fixed.

i just download the latest PyTK mods and now it works thanks xD.

and Space Core people have the same issue, the mod have bugs.

for EntoaroxFramework its latest version sir.

new log : https://smapi.io/log/0da8ff5df6404b6c8e7d5eb5aa9adde1

**Comment by ruleofrose** [comment]
> Hi !
> I'm on Galaxy Tab A 2016, Android 8.1.0 with Stardew Valley 1.4 (maj 7/02/2020) your release 0.9.2
> and it doesn't work :/
> 
> I have this message on SMAPI-lastest.txt
> ![84347382_491253218226912_4724895137237303296_n](https://user-images.githubusercontent.com/50276655/74062170-f2ee4600-49ed-11ea-99a4-d1f786bf6939.jpg)
> 
> I don't understand this :/

Yes you need to wait the smapi 3.0 update

**Comment by ruleofrose** [comment]
>the new somalí suddendly crash :o 
https://smapi.io/log/358db7cc7e1946e087f73dfda455aa4f

**Comment by maiconlik** [comment]
Hi Marty, the newest version 1.4.4.129 doesn't work with smapi, I want to play in this version because many hugs were fixed, will have a new update? Thank you so much for this amazing mod

**Comment by ckgio99** [comment]
Report sir, NPC Adventures (It's time to adventure) not working correctly. I'm using Xperia X Compact & Android 8.
Log here:
https://smapi.io/log/4d92aa0823444176b639b36eec801770

**Comment by MrT3a** [comment]
Regenerated the APK with build 129, SMAPI crashes. 
Here's the log : https://smapi.io/log/6b2dfad6cba949ee87723c990208f652

**Comment by sherks** [comment]
S10+ android 10
Not work . Hope you would release stable version soon. Thanks
https://smapi.io/log/41c94e2b9f56440495094aee0276274e

**Comment by VendettaX5** [comment]
Smapi has crashed on my phone Zenfone Max Pro M1
https://smapi.io/log/0bacbebcd70041e993ae5f5e284b039f

**Comment by kimz1409** [comment]
Xiaomi Mi A2, Android 10
It crash in a loading screen.

https://smapi.io/log/a88b99667bae4579a21d3d1635153dba

**Comment by Lodewolf** [comment]
There is a crash at startup when opening the SMAPI app (console screen before menu).. I tried removing all mods, and it seems the problem is the app itself (probably compatibility problems)

 the base apk works fine

Device: Huawei Honor Play

https://smapi.io/log/c44252b54b9a4cb68f3b3e6183960730

**Comment by ckgio99** [comment]
Report sir, SDV 1.4.4.131 crashed
Log: https://smapi.io/log/4a2cdb0d8fa4441897a9c9cc4402e393

**Comment by MartyrPher** [comment]
Well I had a new version yesterday but seeing as Stardew Valley has been released to everyone. I just submitted it to the releases tab. This solves the issues with the Devs new Singleton "TutorialManager" that caused the crash before.

With 1.4 being released to everyone. If an issue arises, feel free to create a new issue. Since I'm closing this one now.

Cheers!
