### ISSUE TITLE
0.9.2 Crash - No mod folder before opening installer will crash the installer

### ISSUE THREAD

**Issue by Dithreabhach-Cal** [MartyrPher/SMAPI-Android-Installer#36]
Installed Stardew 1.331 fr9m Google Playstore. Installed SMAPI 0.9.2 from here. Whenever I launch SMAPI it crashes.
Running on Samsung Tab A with Android 8.1 os

**Comment by m-truclinh** [comment]
The new version SMAPI 0.9.2 crashed on my phone pixel 3a android version 10, too. 
The game version is the same with the previous commentator.

**Comment by Caco-o-sapo** [comment]
It crashed for me too, I use a Moto g 3

**Comment by CidSilvers** [comment]
It's the same for me, wish there was a solution.

**Comment by Caco-o-sapo** [comment]
I managed to work, I did a force stop on the smapi installer and it worked

**Comment by CidSilvers** [comment]
I got it to work just a minute ago, had to install the previous edition and then update it in order for it to work

**Comment by CidSilvers** [comment]
I got it to work just a minute ago, had to install the previous edition and then update it in order for it to work

**Comment by FTOtter** [comment]
I'm having the same problem on Google pixel 3a. I tried installing the 0.9.1 version, which opened successfully, but when I updated it to 0.9.2 it just crashed again.

**Comment by Ryan-coder** [comment]
Wait ... did you uninstall the old installer then install a new one?

**Comment by FTOtter** [comment]
> Wait ... did you uninstall the old installer then install a new one?

I think I tried both, the directions I had about updating were somewhat unclear.

**Comment by Ryan-coder** [comment]
Try removing it:
- SMAPI Stardew Valley
- SMAPI Android Installer
- All files in the "StardewValley" folder except your Mods And Save Games folder

Ok ... Try doing this
-----------------------------------
1. Install Stardew Valley and SMAPI 0.9.1
2. Enter the SMAPI Installer then press install
3. When the process is complete, don't install the SMAPI Stardew Valley first
4. Now install SMAPI 0.9.2 without removing version 0.9.1
5. Ok ... Try to enter the SMAPI Android Installer then press install ... and when the process is complete, please install the SMAPI Stardew Valley

**Comment by FTOtter** [comment]
> Try removing it:
> 
>     * SMAPI Stardew Valley
> 
>     * SMAPI Android Installer
> 
>     * All files in the "StardewValley" folder except your Mods And Save Games folder
> 
> 
> ## Ok ... Try doing this
> 
>     1. Install Stardew Valley and SMAPI 0.9.1
> 
>     2. Enter the SMAPI Installer then press install
> 
>     3. When the process is complete, don't install the SMAPI Stardew Valley first
> 
>     4. Now install SMAPI 0.9.2 without removing version 0.9.1
> 
>     5. Ok ... Try to enter the SMAPI Android Installer then press install ... and when the process is complete, please install the SMAPI Stardew Valley

I tried that, this time I did get a message about 'do I want to update' from smapi. The first time I tried to run the installer, it closed after asking for permissions again. I tried it again just for kicks, andnir actually worked and installed SMAPI stardew, which seems to now be working (at least, I now have the virtual keyboard present, haven't tried adding mods yet).

**Comment by m-truclinh** [comment]
> > Try removing it:
> > ```
> > * SMAPI Stardew Valley
> > 
> > * SMAPI Android Installer
> > 
> > * All files in the "StardewValley" folder except your Mods And Save Games folder
> > ```
> > 
> > 
> > ## Ok ... Try doing this
> > ```
> > 1. Install Stardew Valley and SMAPI 0.9.1
> > 
> > 2. Enter the SMAPI Installer then press install
> > 
> > 3. When the process is complete, don't install the SMAPI Stardew Valley first
> > 
> > 4. Now install SMAPI 0.9.2 without removing version 0.9.1
> > 
> > 5. Ok ... Try to enter the SMAPI Android Installer then press install ... and when the process is complete, please install the SMAPI Stardew Valley
> > ```
> 
> I tried that, this time I did get a message about 'do I want to update' from smapi. The first time I tried to run the installer, it closed after asking for permissions again. I tried it again just for kicks, andnir actually worked and installed SMAPI stardew, which seems to now be working (at least, I now have the virtual keyboard present, haven't tried adding mods yet).

Thank you very much for the solution.
Also mods which haven't been updated to 1.4 SV patch are working fine :)

**Comment by MartyrPher** [comment]
This is odd, so a fresh install of 0.9.2 installer causes it to crash on startup? Is there any `crash.txt` in the `InternalStorage/SMAPI Installer` folder? I tried to replicate the issue on my Galaxy S10 to no avail.

**Comment by meriluna** [comment]
> This is odd, so a fresh install of 0.9.2 installer causes it to crash on startup? Is there any `crash.txt` in the `InternalStorage/SMAPI Installer` folder? I tried to replicate the issue on my Galaxy S10 to no avail.

I installed 0.9.2 on my Note 9. It immediately crashes on startup. I tried to reinstall it and get the same problem. I don't even have the Internal storage/SMAPI folder listed. The install appears to be successful when I run it.

I'm going to keep trying and I'll update if I get any better info.

**Comment by innerphilim** [comment]
I having this issue too, but somehow it stoped crashing, the ploblem is that after I generate the SMAPI modified game it won't install and android apk installer say that the pagkage is corrupted.

**Comment by MartyrPher** [comment]
@meriluna Hmm, thanks for the info. The Note 9 is pretty darn similar to the S10. I have a Samsung Tablet running 5.0 that I can test on.

**Comment by MartyrPher** [comment]
I have replicated the crash on my Samsung Tab. Will try to post a fix here tomorrow when I have sometime. Cheers!

**Comment by MartyrPher** [comment]
The Hotfix is listed above by @Ryan-coder, another Hotfix is to manually create a `Mods` folder in the `StardewValley/` directory.

**Comment by MartyrPher** [comment]
The new APK is up on the releases tab that addresses this issue. I'm closing this issue now. If the problem still comes around I can reopen this issue. Cheers!
