### ISSUE TITLE
(Release 0.9.1) Force Close after startup

### ISSUE THREAD

**Issue by Emmanuel2008** [MartyrPher/SMAPI-Android-Installer#37]
After i opened the game and clicked my save it crashed:(
(Using Android 9.0)

https://log.smapi.io/v49PMSa9

**Comment by Emmanuel2008** [comment]
This issue is similar to the issue #5

**Comment by MartyrPher** [comment]
Looks like a problem with NPC Map Locations causing the crash. Did you grab the SVE version of it?

**Comment by Emmanuel2008** [comment]
Yes
![Screenshot_20191201-073533_My Files](https://user-images.githubusercontent.com/58358768/69907283-34221280-140d-11ea-9f66-89632380207c.jpg)

**Comment by Emmanuel2008** [comment]
Oh. It works fine now.
https://log.smapi.io/MkJ3xp09
