### ISSUE TITLE
0.9.2 - No Stardew Valley folder causes installer to crash

### ISSUE THREAD

**Issue by MartyrPher** [MartyrPher/SMAPI-Android-Installer#39]
If the user did not create a save file for Stardew Valley, the Stardew Valley folder will not exist. The Installer tries to create the `Mods` folder into a directory that doesn't exist. Causing a crash. Very bad.

**Comment by MartyrPher** [comment]
Suggested Fix: Running Stardew Valley once and creating a save.

**Comment by leoguyman365** [comment]
Oh nevermind ignore my other comment

**Comment by MartyrPher** [comment]
This is fixed in the newest release. Closing this issue unless the problem comes up again.
