### ISSUE TITLE
Update for game version 1.31

### ISSUE THREAD

**Issue by xelrix** [MartyrPher/SMAPI-Android-Installer#4]
Currently the modded apk would not load up.
On huawei p10 emui 9 (android 9)

**Comment by MartyrPher** [comment]
Version 0.8.8 was released for 1.31 game version.

https://github.com/MartyrPher/SMAPI-Android-Installer/releases/tag/0.8.8

**Comment by xelrix** [comment]
The modded stardew valley didn't load at all. I wonder if there's a log file?

**Comment by MartyrPher** [comment]
If it got to SMAPI there should be a SMAPI log in the "StardewValley/ErrorLogs" folder.

**Comment by xelrix** [comment]
That explains why there's no logfile. I didn't get to smapi/logo

**Comment by xelrix** [comment]
Everything seems to work fine. I recommend closing this issue.

**Comment by MartyrPher** [comment]
Interesting. Why it didn't work the first time... They made some changes in the Main Activity this release, might be part of the reason. Thanks for the follow-up!
