### ISSUE TITLE
Doesn't Work

### ISSUE THREAD

**Issue by bodesagaz** [MartyrPher/SMAPI-Android-Installer#41]
![Screenshot_2019-12-25-23-02-05-741_com miui home](https://user-images.githubusercontent.com/59240076/71453772-d498f780-276b-11ea-9734-76c3a3ab3e64.jpg)
![Screenshot_2019-12-25-23-02-22-496_com miui bugreport](https://user-images.githubusercontent.com/59240076/71453779-de225f80-276b-11ea-80b1-8b12a93e0b53.jpg)
Please tell me if I did anything wrong, though I was pretty sure all I had to do was to download and install

**Comment by MartyrPher** [comment]
What version of the game do you have? It's looking for a class that's not there.

**Comment by MartyrPher** [comment]
The OP did not have either the Google Play Version of the game or the wrong version. Closing this issue.
