### ISSUE TITLE
The app orced closed when open cjb item spawner menu

### ISSUE THREAD

**Issue by lesyeuxdejudas** [MartyrPher/SMAPI-Android-Installer#44]
Everytime i open cjb item spawner menu, it always says "smapi Stardew valley isn't responding" . Please explain how to fix this 
Here's the error logs  https://smapi.io/log/888836056c0c42cfa5632d7b64b67d0a

**Comment by MartyrPher** [comment]
That's a known issue with CJB that shouldn't cause the app to crash. I'm not sure there is a fix till 1.4 hits mobile.

**Comment by MartyrPher** [comment]
This is fixed in the new SMAPI and CJB for Stardew Valley 1.4!

Please reopen this issue if it's still causing a crash.
