### ISSUE TITLE
Save Error

### ISSUE THREAD

**Issue by sfrnthrd** [MartyrPher/SMAPI-Android-Installer#45]
i cannot save the latest data, usually when the player sleep it will be auto saved, but mine said that 'Save Error' do you know whats wrong with it?

**Comment by MartyrPher** [comment]
Can you upload your log to https://smapi.io/log/ and post the log link here? Sounds like a mod that's causing that save error message.

**Comment by alessurr** [comment]
i'm having the same problem. is it because of the entaorox framework?

https://smapi.io/log/563880f561124d0197bc40932b0aa010

**Comment by MartyrPher** [comment]
I remember solving this issue on the discord. It was a certain mod that was causing error. It could be entaorox Framework. Feel free to open a new issue if this problem is still floating around.
