### ISSUE TITLE
Unable to download

### ISSUE THREAD

**Issue by usagimomo** [MartyrPher/SMAPI-Android-Installer#47]
When trying to download it downloads about halfway then won't download further and after 5 minutes I get the message under the download notification **forbidden** and I'm not currently able to download it at this moment. Looked cool but guess I was wrong.

**Comment by MartyrPher** [comment]
Github won't let you download the apk of the installer? It could possibly be blocked by your phone to prevent third party apks from installing on the device.

**Comment by MartyrPher** [comment]
OP hasn't responded and seems like an issue with GitHub and not SMAPI or the Installer. Closing this issue.
