### ISSUE TITLE
Force Close When Open Smapi Installer

### ISSUE THREAD

**Issue by TerraMKII** [MartyrPher/SMAPI-Android-Installer#49]
using Galaxy S10 5G (SM-G977N), Android 10
help

**Comment by MartyrPher** [comment]
I have a Galaxy S10 with Android 10 and tested a clean install and it works fine on my end. Is this anyway related to #39?

**Comment by TerraMKII** [comment]
> using Galaxy S10 5G (SM-G977N), Android 10
> help
