### ISSUE TITLE
Spacecore bug?

### ISSUE THREAD

**Issue by igoudz** [MartyrPher/SMAPI-Android-Installer#51]
(sorry for my bad Eng) There's a big bug in my SDV. When i wake up in the morning, the crops always be watered so i cannot water them again. The problem is those watered crops will never grow any further. I noticed this when my parsnip crops are still seed at day 7. I actually install a lot of mods so i remove them one by one and found it's cause by the spacecore. I tested by place only spacecore in /Mods and there's the bug, then remove it and place all of the other mods in /Mods folder and the bug disappear. Redownload the spacecore from nexus and the bug still there. Others thing work just fine though. The SDV is the latest version from playstore, on Huawei P30 (no root). help pls T-T

**Comment by igoudz** [comment]
![Screenshot_20200119_154946_com martyrpher stardewvalley](https://user-images.githubusercontent.com/60059450/72677876-6e399780-3ad3-11ea-87d3-788dc63d91d1.jpg)

**Comment by MartyrPher** [comment]
SpaceCore never was supported in 1.3. A PR has been sent to the author for Android support. Once the author merges the PR, then check to make sure it's working as intended with Stardew Valley 1.4. If it's not working once the update is live, then feel free to create a new issue.

https://github.com/spacechase0/SpaceCore_SDV/pull/10
