### ISSUE TITLE
App won't install

### ISSUE THREAD

**Issue by Natsuki-nakano** [MartyrPher/SMAPI-Android-Installer#61]
Is says app not installed every time I tried to install it. And it also said the game version is 1.4.4.130 :-/ the latest version is 1.4.4.131 pls fix it :-(

**Comment by MartyrPher** [comment]
Do you have the Google Play Store version?

**Comment by Natsuki-nakano** [comment]
Yes I do :-/

**Comment by Natsuki-nakano** [comment]
My current version is 1.4.4.131
