### ISSUE TITLE
Stardew Valley Expanded mod FPS issue

### ISSUE THREAD

**Issue by FiralTheSpiral** [MartyrPher/SMAPI-Android-Installer#63]
Stardew Valley Expanded runs very slowly on my Moto G7 Supra. I have 3gb of ram, and a decent processor.

**Comment by MartyrPher** [comment]
Do you have a SMAPI log? You can find out where to get it from this website. https://smapi.io/log/

**Comment by FiralTheSpiral** [comment]
I do have an SMAPI log.
[SMAPI-latest.txt](https://github.com/MartyrPher/SMAPI-Android-Installer/files/4196341/SMAPI-latest.txt)

**Comment by FiralTheSpiral** [comment]
Oh, wait, wrong thing.

Here it is.

https://smapi.io/log/70a5bf9231d04b8faf3353ef000658d3

**Comment by ohwowweekool** [comment]
I am also suffering from this and trying to find a way to have SVE work on mobile. I'm just not sure it's possible reduce the frame rate issues with such a large mod.

**Comment by MartyrPher** [comment]
This is weird, the only error is TMX Toolkit and that's only when trying to save. I don't see any issues that would cause lag? How bad is it?

**Comment by FiralTheSpiral** [comment]
its bad enough to make it unplayable. it runs at maybe 5 FPS.

**Comment by Erdnussflippi** [comment]
I think spacecore and jssonassets cause the FPS issue, because spacecore is now a necessity for jsonassets and therefore SVE. I got it to work without FPS issues by using a mixture of old and new Jsonassets and spacecore files but I couldnt get it to work a second time (because I added new mods and I had to reload everything, so now I dont actually know what I did anymore). The fact that it worked with maybe other versions? could be an indicator that these two mods cause the lag because they ate the only thing I changed, but Im not an expert on those things. The thing is spacecore never worked well on android phones and now that jsonassets relies on it all jsonassetmods wont work as well. Which sucks because almost every good mod relies on it.

**Comment by Ryan-coder** [comment]
In my opinion ...

Mod SVE has too many files ... and too many mods can cause fps to drop

**Comment by FiralTheSpiral** [comment]
yeah, SVE is a massive mod, but i havent had any issues with about the same amount of mixed mods before. it seems to be a TMXLoader map issue though, because when i remove the custom map/locations mods (TMXLoader is a dependency for them), it runs smooth.

**Comment by maiconlik** [comment]
Hi guys, a fixed the fps issue here is the file, remember to delete your content patcher, PYTK, json assets and etc. http://www.mediafire.com/file/4ng7t5s9fdhlns2/SVE_1.9.4_MOBILE.zip/file

**Comment by Erdnussflippi** [comment]
Why is everything spanish?

**Comment by Erdnussflippi** [comment]
Ok got it to work in english thank you for fixing it maiconlik

**Comment by maiconlik** [comment]
> Ok got it to work in english thank you for fixing it maiconlik

sorry for my mistake, i'm brazilian and i forgot to change the language

**Comment by maiconlik** [comment]
Here's the English version, for anyone interested. Sorry again.
http://www.mediafire.com/file/ydta9gil6rbgwo9/SVE_mobile_english.zip/file

**Comment by maiconlik** [comment]
I edited the comment and put the English version for anyone interested. Sorry again.

**Comment by Ryanika-Coder** [comment]
> Hi guys, a fixed the fps issue here is the file, remember to delete your content patcher, PYTK, json assets and etc. http://www.mediafire.com/file/ydta9gil6rbgwo9/SVE_mobile_english.zip/file

Maybe you can contact the SVE Owner to add an android version

**Comment by DARKASHER** [comment]
> Hi guys, i fixed the fps issue, remember to delete your content patcher, PYTK, json assets and etc. http://www.mediafire.com/file/ydta9gil6rbgwo9/SVE_mobile_english.zip/file

Should i delete them ?? The mod requires them

**Comment by Josemitoo** [comment]
> I edited the comment and put the English version for anyone interested. Sorry again.

Você poderia colocar uma versão PT-BR, disponível pra download?

**Comment by Rayv2020** [comment]
I have been having this issue too. Started after I saved on the first day. I deleted my SpaceCore mod and that helped, it really did... But the downside to this is most of the new structures don't display their text right (e.g. new signs display 'String/String etc.' instead of the the proper text). That is because JSON assests need SpaceCore for it to work. I tried downloading what Maiconlik sent, but it broke my game... So in conclusion, the way to stop the lag is delete SpaceCore, but it will take away some parts of the game.

**Comment by Rayv2020** [comment]
And to add to this, most (if not all) JSON files will not work if you delete SpaceCore, because JSON assets is dependent on it. If you guys have an idea how to play the game without lag, with SpaceCore, that would be great.

**Comment by MartyrPher** [comment]
EvilOfGods mentions a fix for SVE on the discord so I'm posting it here.
The main cause of lag is FarmTypeManager.
`{
  "EnableConsoleCommands": true,
  "EnableContentPacks": true,
  "EnableContentPackFileChanges": true,
  "EnableTraceLogMessages": true,
  "MonsterLimitPerLocation": null
}

1.1 Farm Type Manager mod, standard config for MonsterLimitPerLocation is null, this caused lag for Android, change null to number to limit it, 0 is minimum,  over 600 can cause lag, change to 10 should be ok.`

**Comment by Rayv2020** [comment]
Huh, that fixed it. Well it was that easy. I guess I thought deleting SpaceCore helped because of the JSON files malfunctioning... So it removed some things from other mods... With SpaceCore on, this method helped. Thanks!!!

**Comment by tagarc** [comment]
It worked for me too! Thanks!

**Comment by FiralTheSpiral** [comment]
That worked! Thank you so much!

**Comment by The-Great-Fox** [comment]
> EvilOfGods mentions a fix for SVE on the discord so I'm posting it here.
> The main cause of lag is FarmTypeManager config file.
> 
> > {
> > "EnableConsoleCommands": true,
> > "EnableContentPacks": true,
> > "EnableContentPackFileChanges": true,
> > "EnableTraceLogMessages": true,
> > "MonsterLimitPerLocation": null
> > }
> 
> > 1.1`` Farm Type Manager mod, standard config for MonsterLimitPerLocation is null, this caused lag for Android, change null to number to limit it, 0 is minimum,  over 600 can cause lag, change to 10 should be ok.

Hello guys have this problem in sansung A10, and i would like to know how to do this configuration.
Some one can help me please?

**Comment by SHADOW760** [comment]
hello guys i am having some issues with stardew valley expanded on my moto g5, when i try to play its lagging and I've seen a lot of errors on the console

**Comment by Elmadu** [comment]
Using Android v11 (4 gig RAM) and changing that value in the config file didn't work. MonsterLimitPerLocation was already 10 upon initial opening of the file. Changed it to 0, no change. Ideas?

**Comment by AatroxDarkin** [comment]
> EvilOfGods mentions a fix for SVE on the discord so I'm posting it here. The main cause of lag is FarmTypeManager config file.
> 
> > {
> > "EnableConsoleCommands": true,
> > "EnableContentPacks": true,
> > "EnableContentPackFileChanges": true,
> > "EnableTraceLogMessages": true,
> > "MonsterLimitPerLocation": null
> > }
> 
> > 1.1`` Farm Type Manager mod, standard config for MonsterLimitPerLocation is null, this caused lag for Android, change null to number to limit it, 0 is minimum,  over 600 can cause lag, change to 10 should be ok.

It's work. I change and now the fps is alway 58+, my phone is using snap dragon 632 :)

**Comment by RUNNEARS** [comment]
> EvilOfGods mentions a fix for SVE on the discord so I'm posting it here. The main cause of lag is FarmTypeManager config file.
> 
> > {
> > "EnableConsoleCommands": true,
> > "EnableContentPacks": true,
> > "EnableContentPackFileChanges": true,
> > "EnableTraceLogMessages": true,
> > "MonsterLimitPerLocation": null
> > }
> 
> > 1.1`` Farm Type Manager mod, standard config for MonsterLimitPerLocation is null, this caused lag for Android, change null to number to limit it, 0 is minimum,  over 600 can cause lag, change to 10 should be ok.

no effect on my device. I saw a comment SD 632 can run it. but my SD 662 is not running properly. How could it be ?

Log :
https://smapi.io/log/9bb2f78ed6244e64bb3757efdbbd9ddc

**Comment by Matcha555** [comment]
> EvilOfGods mentions a fix for SVE on the discord so I'm posting it here. The main cause of lag is FarmTypeManager config file.
> 
> > {
> > "EnableConsoleCommands": true,
> > "EnableContentPacks": true,
> > "EnableContentPackFileChanges": true,
> > "EnableTraceLogMessages": true,
> > "MonsterLimitPerLocation": null
> > }
> 
> > 1.1`` Farm Type Manager mod, standard config for MonsterLimitPerLocation is null, this caused lag for Android, change null to number to limit it, 0 is minimum,  over 600 can cause lag, change to 10 should be ok.

Thanks bro. this works on PC as well, still working in 2023.

**Comment by PatrickPhamm** [comment]
> EvilOfGods mentions a fix for SVE on the discord so I'm posting it here. The main cause of lag is FarmTypeManager config file.
> 
> > {
> > "EnableConsoleCommands": true,
> > "EnableContentPacks": true,
> > "EnableContentPackFileChanges": true,
> > "EnableTraceLogMessages": true,
> > "MonsterLimitPerLocation": null
> > }
> 
> > 1.1`` Farm Type Manager mod, standard config for MonsterLimitPerLocation is null, this caused lag for Android, change null to number to limit it, 0 is minimum,  over 600 can cause lag, change to 10 should be ok.

Thanks bro, this works on PC as well, still working in 2023.
