### ISSUE TITLE
Not Installing

### ISSUE THREAD

**Issue by xeasli** [MartyrPher/SMAPI-Android-Installer#68]
The Stardew Valley app I currently have is 1.4.5.136, and when I try to run the SMAPI installer it fails; just says that the app wasn't installed. I don't know if it's actually a problem with the installer itself or if I just need to wait for an update? Anyway, thank you for the hard work!

**Comment by Skishe** [comment]
It seems you have to install 1.4.4.131. I had 1.4.4.136 and it also had the same issue.

So yeah, 1.4.4.131 is the fix

**Comment by xeasli** [comment]
I'm gonna try that, thanks :) Guess I'm just gonna have to wait for a bit more. Thanks again!
