### ISSUE TITLE
Help

### ISSUE THREAD

**Issue by FlavorsofPie** [MartyrPher/SMAPI-Android-Installer#7]
Okay so this is probably the wrong area to put this but I couldn't think of anywhere else for it so here we go. 

How do install mods using this? I went through the installation process and then opened the app and its exactly the same as the unmodded vanilla game. Not sure if I'm missing something or what, but any help resolving this issue is greatly appreciated.

**Comment by MartyrPher** [comment]
Did you read the ReadMe? It gives a brief description of how to install mods and where to put them. If videos are more of your thing, check out this [tutorial](https://www.youtube.com/watch?v=jOXl6Dmu7wY&feature=youtu.be) by Marigolden. Hope this helps.
