### ISSUE TITLE
CFR

### ISSUE THREAD

**Issue by Skishe** [MartyrPher/SMAPI-Android-Installer#70]
Is CFR still not fixed? Seems to display error logs about a missing token

**Comment by MartyrPher** [comment]
Do you have a log?

https://smapi.io/log/

This might have been patched in 3.2.0.3?

**Comment by Skishe** [comment]
Yeah i think the new version just fixed it. There wasnt any kind of error.

Though, the names of the added crafting machines seems to be broken.

Here is the log anyways:
https://smapi.io/log/730d4ad2702c48ccaf07fa25493ba1cc
