### ISSUE TITLE
Very Laggy

### ISSUE THREAD

**Issue by Emmanuel2008** [MartyrPher/SMAPI-Android-Installer#76]
After I resolved my last issue, it made a new one. The game is super laggy and so slow.
https://smapi.io/log/d94bbc9b2b6643f9837604f864680ecb

**Comment by Emmanuel2008** [comment]
![image](https://user-images.githubusercontent.com/58358768/74597614-4cfda400-509d-11ea-886c-301615c31e10.jpg)

**Comment by MartyrPher** [comment]
This is an issue with SVE and FarmTypeManager see the comment on #63
