### ISSUE TITLE
Mod Better Junimo not work 

### ISSUE THREAD

**Issue by ckgio99** [MartyrPher/SMAPI-Android-Installer#78]
Sorry, It not a bug. Better Junimo broken

**Comment by MartyrPher** [comment]
Can you try the newest version and report if it's still broken?

**Comment by ckgio99** [comment]
Yeah, It worked. When I press "Key", a Junimo has spawned but they don't havest crop, they only dancing :D . Pc version has the same issue 
Log: https://smapi.io/log/73611dbd9e0c480f9f87dc02553bf586

**Comment by ckgio99** [comment]
@MartyrPher 
Can I help you translate to Vietnamese?
