### ISSUE TITLE
Add a .nomedia file

### ISSUE THREAD

**Issue by Bredhis** [MartyrPher/SMAPI-Android-Installer#8]
I want to suggest a little quality of life feature:

Could you add a _.nomedia_ file alongside the _Mods_ and _smapi-internal_ folders into the games folder? So that the folder will not be scanned and indexed by other apps on the device, e.g. the gallery app.

Keep up the good work! :)

**Comment by MartyrPher** [comment]
Great Suggestion! One question is why have two of them? Would having just one at the root of `StardewValley` suffice or maybe even just `StardewValley/Mods`?

**Comment by Bredhis** [comment]
One would definitely be enough. Sorry if that has come across differently, English is not my native language. :)

_StardewValley_ as the root folder was what I meant. Putting it in _StardewValley/Mods_ would also be fine, but it might be more prone to accidental deletion by the user in there.

**Comment by MartyrPher** [comment]
This is added in 0.9.0! If it works correctly I can close this issue!

**Comment by Bredhis** [comment]
Updated today, for me it is working correctly.

Thanks a lot. :)

**Comment by MartyrPher** [comment]
Thanks for the follow-up!
