### ISSUE TITLE
Spacecore error

### ISSUE THREAD

**Issue by Skishe** [MartyrPher/SMAPI-Android-Installer#83]
https://smapi.io/log/fa9c3461dc5c447da1bbde705da0cb56

Whats up with "boolean prefix" error?

**Comment by Ryanika-Coder** [comment]
Hi. Spacecore has been updated for the Android version but has not been released on Nexus

This one has been rewritten
https://files.catbox.moe/iecody.zip

**Comment by Ryanika-Coder** [comment]
If your problem is solved ... you can close this issue

**Comment by Skishe** [comment]
Its fixed now and it seems there is also a noticeable improvement on SVE fps.
