### ISSUE TITLE
It keep saying "App not installed" it work before but a some kid delete it 

### ISSUE THREAD

**Issue by BloodCrystalArt** [MartyrPher/SMAPI-Android-Installer#84]
![Screenshot_20200218-231258](https://user-images.githubusercontent.com/61197354/74749432-1f834700-52a5-11ea-8c44-15e10a639ea3.jpg)

**Comment by Skishe** [comment]
Its the apk. Try downloading the apk from browser.

I've also had my issues with this

**Comment by BloodCrystalArt** [comment]
Nope still not working

**Comment by leventebajak** [comment]
Same issue here

**Comment by leventebajak** [comment]
I used a different browser (Armorfly to be specific) to download the launcher and it successfully installed.
I believe Chrome somehow corrupted the installer for me.

**Comment by Trisolam** [comment]
Got the same problem

**Comment by MartyrPher** [comment]
I think this is a problem with the Installer running out of Memory before it successfully completes building the new app. I would try closing out of all the running apps in the background, then try to install again.

I'm currently looking into this issue for a fix.

**Comment by BloodCrystalArt** [comment]
@MartyrPher Im able to download it again :D but the commands not working

**Comment by a66448579** [comment]
> I think this is a problem with the Installer running out of Memory before it successfully completes building the new app. I would try closing out of all the running apps in the background, then try to install again.
> 
> I'm currently looking into this issue for a fix.

Thanks, clearing some of my phone's storage fixed the issue for me.

**Comment by KenWebStudio** [comment]
> > I think this is a problem with the Installer running out of Memory before it successfully completes building the new app. I would try closing out of all the running apps in the background, then try to install again.
> > I'm currently looking into this issue for a fix.
> 
> Thanks, clearing some of my phone's storage fixed the issue for me.

@a66448579  How much storage did you have for it to install properly?

**Comment by a66448579** [comment]
Around 1 - 1.5gb

**Comment by KenWebStudio** [comment]
@a66448579 Damn, I have 25.53GB and it still is not working... :(

**Comment by a66448579** [comment]
I did also close all apps running in background per @MartyrPher's advice. Plus I first uninstalled both SMAPI installer and the previous version of SMAPI stardew, not sure if this had any impact - I was concerned that my phone had blocked permissions for the installer, not sure if this may have been the case.

**Comment by KenWebStudio** [comment]
As for SMAPI version Release 3.2.0.4, the game version required is 1.4.5.139.
I did update the game to version 140 and it worked.

**Comment by lissyloo23** [comment]
Absolutely nothing worked for me, I couldn't get smapi to work on my laptop either even after following the direction dot to dot. So I downloaded on phone did everything right and says app not installed. I literally give up.
