### ISSUE TITLE
Game crashed at startup in SDV 1.4.5.138 (latest Play Store Update)

### ISSUE THREAD

**Issue by kimz1409** [MartyrPher/SMAPI-Android-Installer#89]
Vanilla version is working fine. Game is crashed at game opening with or without using mods.
This is the error log.
https://smapi.io/log/788cc2443131475e80c70eece1fe545d

**Comment by hegelmybagel** [comment]
Yep, happening to me as well. Am about to try to reinstall 1.4.5.137 to see if that gets past this crash until a fix is available

**Comment by iggyd64** [comment]
Same problem here too. Nothing works; totally reinstalling everything leads to the same draw loop crash as seen in the log on this issue.

**Comment by JackOpixel** [comment]
Same.. ;(

**Comment by sherks** [comment]
Just wait for new release :D

**Comment by gameison84** [comment]
Oh yes, finally release out! Thanks

**Comment by JejomarPlayz** [comment]
Same:::(

**Comment by JackOpixel** [comment]
Tx!!!

**Comment by MartyrPher** [comment]
This is fixed in the latest release for 1.4.5.139. Closing this issue.
