### ISSUE TITLE
Potential Issue

### ISSUE THREAD

**Issue by Kendjelic** [MartyrPher/SMAPI-Android-Installer#9]
Hello Chris,

Pathoschild recommended I reach out as I have been experiencing some issues when attempting to run his mod Chests Anywhere.  Please see my Nexus post below.

I made the switch from Zane's SMDroid to Martypher's SMAPI fork and the only issue I am running into at the moment is that when I use the button assigned to your mod I receive an in-game message pop-up stating "something went wrong handling key input". Now the buttons I have assigned for other mods work without issue so I know I am assigning them correctly for use with Virtual Keyboard but unsure what the issue is here. Any thoughts? Needless to say I can't live without your mod! Thanks in advance.

https://log.smapi.io/zpfpjCK9

Pathoschild:
That seems to be due to a change in the game code on Android which may affect a number of mods. I suggest letting MartyrPher know, in case it's something SMAPI on Android can rewrite for compatibility.

**Comment by MartyrPher** [comment]
Posting this here as well

>  So Chests Anywhere is something I looked into a while ago and actually added in the needed rewriter here https://github.com/MartyrPher/SMAPI/blob/android/src/SMAPI/Metadata/InstructionMetadata.cs#L66. It seems like the rewriter doesn't want to rewrite for ItemGrabMenu (which is what's causing the mod to fail). Unless I messed something up, I think the only way is to fork it and make the necessary changes.

**Comment by MartyrPher** [comment]
Chests Anywhere has been sent a PR here https://github.com/Pathoschild/StardewMods/pull/520 for Android support. It's in testing now. Closing this issue.
