### ISSUE TITLE
): SDV 1.4.5.1.138 SMAPI Doesn't Work :(

### ISSUE THREAD

**Issue by JejomarPlayz** [MartyrPher/SMAPI-Android-Installer#91]
LOG IS HERE PLEASE HELP ME!! :(
https://smapi.io/log/875d5f7454d744368b796a5d702e288e

**Comment by momoyuki** [comment]
Update content patcher

**Comment by MartyrPher** [comment]
Update Content Patcher, Stardew Valley and SMAPI.

**Comment by JejomarPlayz** [comment]
Solved Problem
